### Site metadata

# Don't make the title longer than this, otherwise it gets covered in mobile view.
title: Sharc
description: Insights into the world of web3 and Decentralization of different platforms.

email: iarunavaofficial@gmail.com
twitter_username: amArunava
linkedin_username: iarunava
instagram_username: imarunava
github_username: iarunava
rss: RSS

### Build settings

url: https://sharc.attim.in
#url: https://iarunava.github.io
# ENABLE baseurl when hosting on github pages
#baseurl: /sharcblog
#

google_analytics: G-878TSV9XZ9

permalink: pretty

remote_theme: jekyll/minima
theme: minima

minima:
  skin: dark

show_excerpts: true

plugins:
  - jekyll-feed
  - jekyll-sitemap

collections:
  #tools:
    #output: true
  #languages:
    #output: true
  shorts:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: page

disqus:
  shortname: sharc

exclude:
  - docs/
  - vendor/
  - Gemfile # Gemfile.lock is implied because of how matching works.
  - LICENSE
  - Makefile
  - README.md
  - sample*.png

liquid:
  error_mode: strict

strict_front_matter: true
